In [6]:
df2=pd.DataFrame(df.groupby(['base_cat'])['record'].value_counts())

In [7]:
# row 생략 없이 출력
pd.set_option('display.max_rows', None)
# col 생략 없이 출력
pd.set_option('display.max_columns', None)

In [8]:
df3=pd.DataFrame(df2.values[0::2],columns=['O'])
df4=pd.DataFrame(df2.values[1::2],columns=['X'])
df5=pd.DataFrame(df2.values[1::2]+df2.values[0::2],columns=['총계'])

df3.index=df['base_cat'].unique()
df4.index=df['base_cat'].unique()
df5.index=df['base_cat'].unique()

pd.concat([df3,df4,df5],axis=1)

     O   X  총계
긍정  28  22  50
부정  27  23  50
A1  27  23  50
A2  27  23  50
A3  27  23  50
A4  26  24  50
B1  26  24  50
B2  33  17  50
B3  27  23  50
B4  32  18  50
B5  26  23  49
B6  25  25  50
B7  33  17  50
C1  28  22  50
C2  31  19  50
C3  25  25  50
C4  26  24  50
C5  27  23  50
C6  30  20  50
C7  27  23  50
C8  26  24  50
D1  31  19  50
D2  28  22  50
D3  26  24  50
E1  30  20  50
E2  34  16  50
E3  26  24  50
E4  27  23  50
F1  27  23  50
F2  31  19  50
F3  27  23  50
F4  27  23  50
G1  28  22  50
G2  26  24  50
G3  25  24  49
G4  32  18  50
G5  35  15  50
G6  28  22  50